### ISSUE TITLE
510_de is the wrong text

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat-guidelines#3]
English seem to be correct.

**Comment by jenniferward** [comment]
The German text for 510 looks correct (if slightly outdated) on the guidelines website http://guidelines.rism.info/admin/documents/5309/edit . Stephan should take a look at it.

**Comment by HirschSt** [comment]
I think it's fixed now; at an early stage 490 was reassigned to 510, leading to this issue. It's probably better to create a new guideline and not to overwrite an existing one.
